[package]
name = "text-transliterate"
version = "0.1.0"
authors = ["David Bonet <webbonet@gmail.com>"]

[dependencies]
libc = "0.2"
locale = "0.2"
iconv = { git = 'https://github.com/y-stm/rust-iconv' }
